config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'products#index'
  resources :products do
    resources :orders
    resources :reviews
  end
  resources :orders, only: %i[index destroy buy]

  # admin

  namespace :admin do
    resources :products, only: %i[create update destroy]
  end
  resources :comments, only: %i[destroy index show] do
    patch 'approve', on: :member
  end
  resources :users, only: %i[create update destroy index show] do
  end

  # customer
namespace :customer do
  resources :products, only: [] do
    resource :review, only: %i[create destroy]
  end
  resources :orders, only: %i[index show]
  resources :users, only: [] do
    resources :comments, only: %i[create]
  end
  resources :comments, only: %i[index show]
  resource :cart, only: [:show] do
    resources :line_items, only: %i[update destroy] do
    end
    post 'checkout', on: :member
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :reviews
  enum rol: [:"User", :"Admin"]
  before_create :user_default
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

private
  def user_default
    self.rol = :"User"
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show destroy]

  def index
    @orders = current_user.Admin? ? Order.all : current_user.orders.group(:id)
    @total_amount = 0
  end

  def new
    @order = Order.new
  end

  def create
    @product = Product.find(params[:product_id])
    ord = Order.where('product_id = ?', @product.id).first
    @order = Order.new(order_params)
    if ord.nil?
      @order.product = @product
      @order.user = current_user
      if @order.quantity <= @product.stock
        @product.binnacle << ",PRODUCT STOCK SUBSTRACTION IN #{@order.quantity} BY USER #{current_user.id} AT #{Time.current} "
        @product.stock -= @order.quantity
      else
        @order.quantity = @product.stock
        @product.binnacle << ",PRODUCT STOCK UPDATE TO 0 BY USER #{current_user.id} AT #{Time.current} "
        @product.stock = 0
      end

    elsif @order.quantity <= @product.stock
      ord.quantity += @order.quantity
      @product.binnacle << ",PRODUCT STOCK SUBSTRACTION IN #{@order.quantity} BY USER #{current_user.id} AT #{Time.current} "
      @product.stock -= @order.quantity
      @order = ord
    else
      ord.quantity += @product.stock
      @product.binnacle << ",PRODUCT STOCK UPDATE TO 0 AT #{Time.current} "
      @product.stock = 0
      @order = ord

    end
    @product.save
    if @order.save
      redirect_to orders_path
    else
      render 'products/show'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    unless params[:buy].present?
      pr = Product.find(@order.product_id)
      pr.binnacle << ",PRODUCT STOCK ADDED IN #{@order.quantity} BY USER#{current_user.id} AT #{Time.current} "
      pr.stock += @order.quantity
      pr.save
    end
    pr = Product.find(@order.product_id)
    pr.binnacle << ",PRODUCT BUY IN #{@order.quantity} BY USER#{current_user.id} AT #{Time.current} "
    @order.destroy
    redirect_to orders_path
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:quantity, :met)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  respond_to :html
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create edit]

  def index
    @products = if params[:sort_by_name].present?
                  if params[:sort_by_name] == 'ASC'
                    Product.order('name ASC')
                  else
                    Product.order('name DESC')
                  end
                elsif params[:commit].present?
                  Product.where('name = ?', params[:query])
                else
                  Product.order('created_at DESC')
                end
  end

  def show
    @review = Review.new
    @order = Order.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.binnacle = "CREATE AT #{Time.current} "
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @product.binnacle += ",PRODUCT EDITED #{params[:id]} AT #{Time.current} "
  end

  def update
    @product = Product.find(params[:id])
    @product.binnacle += ",PRODUCT UPDATE [#{product_params}] AT #{Time.current} "
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.binnacle += ",PRODUCT DESTROY AT #{Time.current} "
    @product.destroy
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:sku, :name, :description, :price, :stock, :binnacle)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @review = Review.new
    rev = Review.where("product_id = ? AND user_id = #{current_user.id}", params[:product_id]).first
    if rev.nil?
      @review.product = @product
      @review.user = current_user
      @review.score = if params[:commit] == 'Like'
                        @product.binnacle += ",PRODUCT LIKE BY USER #{current_user.id} "
                        @product.save!
                        @review.score.to_i + 1
                      else
                        @product.binnacle += ",PRODUCT DISLIKE BY USER #{current_user.id} "
                        @product.save!
                        @review.score.to_i - 1
                      end
    else
      @review = rev
    end

    if @review.save
      redirect_to product_path(@product)
    else
      render 'products/show'
    end
  end

  def new
    @review = Review.new
  end

  def index; end

  def destroy
    @review.destroy
    redirect_to product_path(params[:product_id])
  end

  private

  def review_params
    params.require(:product_id).permit(:commit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row row-cols-3">
  <% @products.each do |product|%>
    <div class="col">
        <div class="card" style="width: 18rem;">
        <%= link_to product_path(product) do %>
        <%= image_tag('https://cdn5.vectorstock.com/i/1000x1000/84/34/chips-snack-line-icon-vector-37588434.jpg', class: 'card-img-top', style: 'background-color: black;') %>
      <% end %>
        <div class="card-body">
        <h5 class="card-title"><%=product.name%></h5>
        <p class="card-text">$<%=product.price%></p>
        <a href="#" class="dropdown-item">Add to cart</a>
      </div>
    </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snack store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "styles"%>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/">Snack Store!</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
            <li class="nav-item">
              <% if !user_signed_in? %>
                <%= link_to 'Log in', user_session_path, class: 'dropdown-item' %>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                </li>
              <% end %>
            </li>
          </ul>
          <% if user_signed_in? %>
            <form class="d-flex" >
              <a class="btn btn-light mx-1" href="/orders" role="button">Cart</a>
            </form>
          <% end %>
        </div>
      </div>
    </nav>
    <header class="bg-dark py-4">
      <div class="container px-4 px-lg-4 my-5">
        <div class="text-center text-white">
          <h1 class="display-4 fw-bolder">The best snacks for you!</h1>
          <p class="lead fw-normal text-white-50 mb-0">Why not one more?</p>
        </div>
      </div>
    </header>
    <p class="notice alert-light"><%=notice%></p>
    <p class="alert alert-light" role="alert"><%=alert%></p>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Cart!</h1>
<% a = 5 %>
<div class=order-container>
  <table class="order-table table">
    <thead class="thead-dark text-center">
      <tr>
        <th scope="col">Nº</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total</th>
        <th scope="col">Date</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody class='text-center'>
      <% @orders.each_with_index do |order, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= order.product.name %></td>
          <td>$ <%= order.product.price %> </td>
          <% @total_amount += order.product.price * order.quantity %>
          <td><%= order.quantity %></td>
          <td>$ <%= order.product.price * order.quantity %></td>
          <td><%= order.created_at.to_s.slice(0, order.created_at.to_s.length - 7) %></td>
          <td>
            <%= button_to "Delete", {:controller => :orders,
                  :action => 'destroy', :id => order.id}, :method => :delete,
                  class: 'btn btn-light mx-1' %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <% if @total_amount > 0 %>
      <tfoot>
        <tr>

          <td class='order-total'>TOTAL</td>
          <td class='order-total-amount'>$ <%= @total_amount %></td>
          <td style='background-color: #343A3F'>
          <td>
            <%= button_to "Buy", {:controller => :orders,
                  :action => 'destroy', :id => @orders.ids , :buy => 1}, :method => :delete,
                  class: 'btn btn-light mx-1'%>
          </td>
          </td>
        </tr>
      </tfoot>
    <% end %>
  </table>
</div>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<div class='user-form'>
    <%= simple_form_for(@product) do |f| %>
    <div class="form-inputs">
        <%= f.input :sku, label: 'SKU' %>
        <%= f.input :name %>
        <%= f.input :description, as: :text %>
        <%= f.input :price %>
        <%= f.input :stock %>
    </div>
    
    <div class="form-actions">
        <%= f.submit 'Update product', class: 'btn btn-primary' %>
    </div>
    <% end %>
</div>

app/views/products/index.html.erb
<% if user_signed_in? && current_user.Admin? %>
  <%= link_to 'CREATE PRODUCT', new_product_path, class:"btn btn-light mx-1"%>
<% end %>
<%= form_with url: "/products", method: :get do |form| %>
  <%= form.label :query, "Search product:" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>
<div class="btn-group" role="group" aria-label="Basic example">
  <div class="d-flex justify-content-around">
    <%= link_to 'Sort by Name ASC', products_path(sort_by_name: 'ASC') , class:'btn btn-light'%>
  </div>
  <div class="d-flex justify-content-around">
    <%= link_to 'Sort by Name DESC', products_path(sort_by_name: 'DESC') , class:'btn btn-light'%>
  </div>
</div>
<div class="container">
  <div class="row row-cols-3">
    <% @products.each do |product|%>
      <div class="col">
        <div class="card focus" style="width: 18rem;">
          <%= link_to product_path(product) do %>
            <%= image_tag('https://cdn5.vectorstock.com/i/1000x1000/84/34/chips-snack-line-icon-vector-37588434.jpg', class: 'card-img-top', style: 'background-color: black;') %>
          <% end %>
          <% if product.stock == 0 %>
            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sold out</div>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%=product.name%></h5>
            <p class="card-text">$<%=product.price%></p>
            <div class='product-card-buttons'>
              <%= link_to 'Buy product', product_path(product), class:'btn btn-light' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>Insert new product</h1>

<div class='user-form'>
    <%= simple_form_for(@product) do |f| %>
    <div class="form-inputs">
        <%= f.input :sku, label: 'SKU' %>
        <%= f.input :name %>
        <%= f.input :description, as: :text %>
        <%= f.input :price %>
        <%= f.input :stock %>
    </div>
    
    <div class="form-actions">
        <%= f.submit 'Add product', class: 'btn btn-primary' %>
    </div>
    <% end %>
</div> 

app/views/products/show.html.erb
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="https://cdn5.vectorstock.com/i/1000x1000/84/34/chips-snack-line-icon-vector-37588434.jpg" class="img-fluid rounded-start" alt="">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%=@product.name%></h5>
        <p class="card-text"><%=@product.description%></p>
        <p class="card-text">$<%=@product.price%></p>
        <p class="card-text">Stock: <%=@product.stock%></p>
        <div class='order-buy-form'>
          <%= simple_form_for([ @product, @order ]) do |f| %>
            <%= f.input :quantity, input_html: { value: 1 } %>
            <% if @product.stock? %>
              <div class='text-right mt-3'>
                <%= f.submit 'Buy', class: 'btn btn-light mx-1' %>
              </div>
            <% end %>
          <% end %>
          <% if user_signed_in? %>
            <%= simple_form_for([ @product, @review ], remote: true) do |f| %>
              <div class='text-right mt-2'>
                <%= f.button :submit, "Like", class: 'btn btn-light mx-1' %>
              </div>
              <div class='text-right mt-2'>
                <%= f.button :submit, "Dislike", class: 'btn btn-light mx-1' %>
              </div>
            <% end %>
          <% end %>
          <% if @product.reviews.exists? %>
            <%="Reviews: #{(@product.reviews.sum(:score)*100)/@product.reviews.count(:score)}%"%>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: <%="#{(@product.reviews.sum(:score)*100)/@product.reviews.count(:score)}%"%>" aria-valuenow=<%="#{(@product.reviews.sum(:score)*100)/@product.reviews.count(:score)}%"%> aria-valuemin="0" aria-valuemax="100"><%="#{(@product.reviews.sum(:score)*100)/@product.reviews.count(:score)}%"%></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
<% if user_signed_in? && current_user.Admin? %>
  <%= link_to 'Edit', edit_product_path(@product), class:'btn btn-secondary mx-1'%>
  <%= button_to "Delete", {:controller => :products,
                  :action => 'destroy', :id => @product.id }, :method => :delete,
                  class: 'btn btn-secondary mx-1' %>
  <%= @product.binnacle%>
<% end %>
</div>
</div>
</div>

app/views/reviews/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Review#destroy</h1>
<p>Find me in app/views/review/destroy.html.erb</p>

app/views/reviews/index.html.erb
<h1>Review#index</h1>
<p>Find me in app/views/review/index.html.erb</p>